-- MySQL Script generated by MySQL Workbench
-- Thu May  7 10:38:50 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema EGNSS4CAP
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema EGNSS4CAP
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `EGNSS4CAP` DEFAULT CHARACTER SET utf8 ;
USE `EGNSS4CAP` ;

-- -----------------------------------------------------
-- Table `EGNSS4CAP`.`pa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EGNSS4CAP`.`pa` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `timestamp` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EGNSS4CAP`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EGNSS4CAP`.`user` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `pa_id` BIGINT NOT NULL,
  `login` VARCHAR(255) NOT NULL,
  `pswd` VARCHAR(255) NOT NULL,
  `name` VARCHAR(255) NULL,
  `surname` VARCHAR(255) NULL,
  `identification_number` INT(10) NULL,
  `email` VARCHAR(255) NULL,
  `vat` VARCHAR(45) NULL,
  `timestamp` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_pa_idx` (`pa_id` ASC),
  CONSTRAINT `fk_pa`
    FOREIGN KEY (`pa_id`)
    REFERENCES `EGNSS4CAP`.`pa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EGNSS4CAP`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EGNSS4CAP`.`role` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `role` VARCHAR(255) NOT NULL,
  `description` VARCHAR(2000) NULL,
  `timestamp` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EGNSS4CAP`.`user_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EGNSS4CAP`.`user_role` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT NOT NULL,
  `role_id` BIGINT NOT NULL,
  `timestamp` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_idx` (`user_id` ASC),
  INDEX `fk_role_idx` (`role_id` ASC),
  CONSTRAINT `fk_ur_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `EGNSS4CAP`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ur_role`
    FOREIGN KEY (`role_id`)
    REFERENCES `EGNSS4CAP`.`role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EGNSS4CAP`.`task`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EGNSS4CAP`.`task` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT NOT NULL,
  `created_id` BIGINT NOT NULL,
  `status` ENUM('new', 'open', 'data provided', 'data checked', 'closed') NOT NULL DEFAULT 'new',
  `name` VARCHAR(255) NULL,
  `text` TEXT NULL,
  `date_created` DATETIME NULL,
  `task_due_date` DATETIME NULL,
  `note` TEXT NULL,
  `timestamp` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_id_idx` (`user_id` ASC),
  INDEX `fk_uid_created_idx` (`created_id` ASC),
  CONSTRAINT `fk_ta_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `EGNSS4CAP`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ta_created`
    FOREIGN KEY (`created_id`)
    REFERENCES `EGNSS4CAP`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EGNSS4CAP`.`photo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EGNSS4CAP`.`photo` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `task_id` BIGINT NOT NULL,
  `lat` FLOAT(10,6) NULL,
  `lng` FLOAT(10,6) NULL,
  `file_name` VARCHAR(255) NOT NULL,
  `timestamp` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_task_id_idx` (`task_id` ASC),
  CONSTRAINT `fk_ph_task`
    FOREIGN KEY (`task_id`)
    REFERENCES `EGNSS4CAP`.`task` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EGNSS4CAP`.`pa_flag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EGNSS4CAP`.`pa_flag` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `flag` VARCHAR(45) NOT NULL,
  `timestamp` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EGNSS4CAP`.`task_flag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EGNSS4CAP`.`task_flag` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `task_id` BIGINT NOT NULL,
  `flag_id` BIGINT NOT NULL,
  `timestamp` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_task_id_idx` (`task_id` ASC),
  INDEX `fk_flag_id_idx` (`flag_id` ASC),
  CONSTRAINT `fk_tf_task`
    FOREIGN KEY (`task_id`)
    REFERENCES `EGNSS4CAP`.`task` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tf_flag`
    FOREIGN KEY (`flag_id`)
    REFERENCES `EGNSS4CAP`.`pa_flag` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
